name: Build

on:
  pull_request: {}
  push:
    branches:
      - master

jobs:
  go-build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4

      - uses: actions/setup-go@v5
        with:
          go-version-file: go.mod

      - name: Run build
        run: go build -v ./...
